// <auto-generated />
using EFCore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.Migrations
{
    [DbContext(typeof(DataDBContext))]
    [Migration("20200315024337_AddData3")]
    partial class AddData3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("EFCore.Model.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProvinceID");

                    b.Property<string>("areaCode");

                    b.Property<string>("name");

                    b.HasKey("ID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ProvinceID = 1,
                            name = "汕头"
                        },
                        new
                        {
                            ID = 2,
                            ProvinceID = 1,
                            name = "广州"
                        },
                        new
                        {
                            ID = 3,
                            ProvinceID = 1,
                            name = "深圳"
                        });
                });

            modelBuilder.Entity("EFCore.Model.Province", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<int>("population");

                    b.HasKey("ID");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            name = "广东",
                            population = 9000000
                        },
                        new
                        {
                            ID = 2,
                            name = "福建",
                            population = 8000000
                        });
                });

            modelBuilder.Entity("EFCore.Model.City", b =>
                {
                    b.HasOne("EFCore.Model.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
